### ISSUE TITLE
Scanner fails to pull Git submodules

### ISSUE THREAD

**Issue by voidpetal** [oss-review-toolkit/ort#10426]
### Describe the bug

When there is a repo with Git submodules, the scanner fails to pull them and produces `Git submodule at 'app/libraries' not initialized` warning. Then the submodule is not scanned.

This is the example repo with the submodule warning:
- [main](https://gitlab.com/sergey.burnevsky/ort-test-main/-/tree/main?ref_type=heads)
- [submodule](https://gitlab.com/sergey.burnevsky/ort-test-libs/-/tree/main?ref_type=heads)

### To Reproduce

1. Run scanner on main repo

### Expected behavior

The submodule is initialized correctly and the repository is fully scanned.

### Console / log output

```
[DefaultDispatcher-worker-1] WARN  org.ossreviewtoolkit.plugins.versioncontrolsystems.git.GitWorkingTree - Git submodule at 'app/libraries' not initialized. Cannot recursively list its submodules.
```

### Environment
* ORT version: 59.3.0
* Java version: 21
* OS: MacOS, Linux

**Comment by sschuberth** [comment]
Can you share the analyzer result for convenience?

**Comment by voidpetal** [comment]
Sure, here you can find the analyzer and scan results, appended `.txt`, as `.yml` file upload is not allowed.

[analyzer-result.yml.txt](https://github.com/user-attachments/files/20587643/analyzer-result.yml.txt)
[scan-result.yml.txt](https://github.com/user-attachments/files/20587659/scan-result.yml.txt)

**Comment by voidpetal** [comment]
Hi @sschuberth, any updates on this? Thanks!

**Comment by sschuberth** [comment]
No, I'm not aware of anyone working on this. If you want to prioritize this, feel free to reach out to me by mail (you can get it from the Git history) to discuss some options. I'm also in contact with @bennati in this regard.

**Comment by sschuberth** [comment]
I see that the syntax being used in your `.gitmodules` file is

```
[submodule "app/libraries"]
	path = app/libraries
	url = ../ort-test-libs
```

So the `url` is relative. While [according to the spec that's allowed](https://git-scm.com/docs/gitmodules#Documentation/gitmodules.txt-submodulenameurl), it's a bit unusual, and I wonder whether the problem goes away when using regular absolute URLs.

**Comment by sschuberth** [comment]
Ah, there we have it, I believe, looking at the analyzer result's `repository` section:

```yaml
repository:
  vcs:
    type: "Git"
    url: "https://gitlab.com/sergey.burnevsky/ort-test-main.git"
    revision: "fa1b28e775d5cff417508b27975b380977d97d6f"
    path: ""
  vcs_processed:
    type: "Git"
    url: "https://gitlab.com/sergey.burnevsky/ort-test-main.git"
    revision: "fa1b28e775d5cff417508b27975b380977d97d6f"
    path: ""
  nested_repositories:
    app/libraries:
      type: "Git"
      url: "git@gitlab.com:sergey.burnevsky/ort-test-libs"
      revision: "6095c61350564683cc2d93fd1175e1b15067ca5f"
      path: ""
  config: {}
```

So the `nested_repositories` is properly recognized, however the relative URL is resolved to use SSH instead of HTTPS as the transport. As I guess that no SSH credentials were configured, naturally the submodule checkout fails.

The underlying question now is: Why does the submodule use SSH, if the superproject’s origin repository uses HTTPS? Guessing further, maybe you have some kind of URL replacement configured, which does not work for submodules (could be related to https://github.com/oss-review-toolkit/ort/issues/8918).

**Comment by voidpetal** [comment]
Hi @sschuberth, thanks for looking into this!

Seems like the git submodule was initialized locally with SSH, and this got reproduced in the remote. After changing the SSH to HTTPS URL with `git submodule set-url app/libraries https://gitlab.com/sergey.burnevsky/ort-test-libs.git` the submodule warning seems to have disappeared.

However we are still encountering ann issue that the submodule is duplicated as reported [here](https://github.com/oss-review-toolkit/ort/issues/10427)

**Comment by sschuberth** [comment]
> However we are still encountering ann issue that the submodule is duplicated as reported [here](https://github.com/oss-review-toolkit/ort/issues/10427)

Ok, but as that's tracked separately, are we good to close this issue?

**Comment by voidpetal** [comment]
Absolutely :)
