### ISSUE TITLE
Docker build failed - ERROR [stage-1 6/6] RUN tar xf /opt/ort.tar -C /opt/ort --strip-comp  95.8s

### ISSUE THREAD

**Issue by BennyThink** [oss-review-toolkit/ort#3226]
# Environment
docker verison
```bash
Client:
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.13.8
 Git commit:        afacb8b7f0
 Built:             Wed Oct 14 19:43:43 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.8
  Git commit:       afacb8b7f0
  Built:            Wed Oct 14 16:41:21 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.3-0ubuntu2
  GitCommit:
 runc:
  Version:          spec: 1.0.1-dev
  GitCommit:
 docker-init:
  Version:          0.18.0
  GitCommit:
```

host version
```bash
{14:38}~/ort:master ✗ ➭ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04 LTS
Release:	20.04
Codename:	focal
```
# build output
using the latest commit

```bash
DOCKER_BUILDKIT=1  docker build -t ort .
=> ERROR [stage-1 6/6] RUN tar xf /opt/ort.tar -C /opt/ort --strip-comp  95.8s
------
 > [stage-1 6/6] RUN tar xf /opt/ort.tar -C /opt/ort --strip-components 1 &&     rm /opt/ort.tar &&     /opt/ort/bin/ort requirements:
#18 2.432 WARNING: An illegal reflective access operation has occurred
#18 2.432 WARNING: Illegal reflective access by retrofit2.Platform (file:/opt/ort/lib/retrofit-2.9.0.jar) to constructor java.lang.invoke.MethodHandles$Lookup(java.lang.Class,int)
#18 2.432 WARNING: Please consider reporting this to the maintainers of retrofit2.Platform
#18 2.432 WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
#18 2.432 WARNING: All illegal access operations will be denied in a future release
#18 2.856 ________ _____________________
#18 2.856 \_____  \\______   \__    ___/ the OSS Review Toolkit, version 0.1.0-SNAPSHOT.
#18 2.856  /   |   \|       _/ |    |    Running 'requirements' under Java 11.0.8 on Linux with
#18 2.856 /    |    \    |   \ |    |    ORT_CONFIG_DIR = /root/.ort/config
#18 2.856 \_______  /____|_  / |____|    ORT_DATA_DIR = /root/.ort
#18 2.856         \/       \/
#18 2.856 More environment variables:
#18 2.856 http_proxy = http://proxy.vmware.com:3128
#18 2.856 https_proxy = http://proxy.vmware.com:3128
#18 2.856 JAVA_HOME = /opt/java/openjdk
#18 2.856 ANDROID_HOME = /opt/android-sdk
#18 2.856 GOPATH = /go
#18 2.856
#18 3.245 Scanners:
#18 3.251 	- Askalono: Requires 'askalono' in version =0.4.3. Tool not found.
#18 3.252 	- BoyterLc: Requires 'lc' in version =1.3.1. Tool not found.
#18 3.252 	- Licensee: Requires 'licensee' in version =9.13.0. Tool not found.
#18 4.933 	* ScanCode: Requires 'scancode' in version =3.2.1-rc2. Found version 3.2.1-rc2.
#18 4.933
#18 4.933 PackageManagers:
#18 4.934 	- Bower: Requires 'bower' in version =1.8.8. Tool not found.
#18 5.169 	* Bundler: Requires 'bundle' in version >=1.16.0 <2.2.0. Found version 1.16.1.
#18 5.191 	* Cargo: Requires 'cargo' in no specific version. Found version 1.43.0.
#18 5.880 	* Conan: Requires 'conan' in version =1.18.0. Found version 1.18.0.
#18 5.887 	* GoDep: Requires 'dep' in no specific version. Found version 0.5.4.
#18 5.894 	* GoMod: Requires 'go' in no specific version. Found version 1.13.4.
#18 6.107 	* Npm: Requires 'npm' in version >=5.7.0 <6.15.0. Found version 6.14.8.
#18 6.258 	* PhpComposer: Requires 'composer' in version >=1.5.0. Found version 1.6.3.
#18 7.080 	* Pip: Requires 'pip' in no specific version. Found version 9.0.1.
#18 7.472 	* Pipenv: Requires 'pipenv' in version >=2018.10.9. Found version 2018.11.26.
#18 7.587 	* Pub: Requires 'pub' in version >=2.2.0. Found version 2.7.2.
#18 94.72 	* Sbt: Requires 'sbt' in version >=0.13.0. Found version 1.3.8.
#18 94.73 	* Stack: Requires 'stack' in version >=2.1.1. Found version 2.1.3.
#18 94.73 	- Yarn: Requires 'yarn' in version >=1.3.0 <1.23.0. Tool not found.
#18 94.73
#18 94.73 VersionControlSystems:
#18 94.74 	* Cvs: Requires 'cvs' in no specific version. Found version 1.12.13.
#18 94.75 	* Git: Requires 'git' in no specific version. Found version 2.17.1.
#18 94.92 	* GitRepo: Requires 'repo' in no specific version. Found version 2.8 (launcher).
#18 95.00 	* Mercurial: Requires 'hg' in no specific version. Found version 4.5.3.
#18 95.00
#18 95.00 Other tools:
#18 95.00 	* PythonVersion: Requires 'python3' in no specific version. Found version 3.6.9.
#18 95.05 	* VirtualEnv: Requires 'virtualenv' in version >=15.1.0 <20.1.0. Found version 15.1.0.
#18 95.05
#18 95.05 Prefix legend:
#18 95.05 	- The tool was not found in the PATH environment.
#18 95.05 	+ The tool was found in the PATH environment, but not in the required version.
#18 95.05 	* The tool was found in the PATH environment in the required version.
#18 95.05
#18 95.05 Not all tools were found in their required versions.
------
failed to solve with frontend dockerfile.v0: failed to solve with frontend gateway.v0: rpc error: code = 
Unknown desc = failed to build LLB: executor failed running [/bin/sh -c tar xf /opt/ort.tar -C /opt/ort --strip-components 1 &&  
   rm /opt/ort.tar &&     /opt/ort/bin/ort requirements]: runc did not terminate successfully
*[master][~/ort]$
*[master][~/ort]$
```

# possible solution
During my investigation, the last command `/opt/ort/bin/ort requirements` will detect related environment setup. However in my test, this command will return non-zero exit code, so the docker daemon will assume this build as a failure.

From my understanding, does this above non-zero exit code means that ort may not work properly? And if the answer is yes, what may possibly cause this issue?

By the way, I did some more research. It appears the base image `adoptopenjdk:11-jre-hotspot-bionic` was Ubuntu 20:04 yesterday, and today it's Ubuntu 18:04, they [correct the issue shortly](https://github.com/AdoptOpenJDK/openjdk-docker/commit/3d1ede905560fce6988fda839cc8da25ab4b73cb#diff-095c8dd27574039e458d8408cf88d97ca036ca4723662405ef1096ecee92e003L20).  So maybe it's related to upstream image? Maybe Canonical has changed something in package index? 

Any insights on this issue would be extremely helpful. Thanks in advance!

**Comment by sschuberth** [comment]
> From my understanding, does this above non-zero exit code means that ort may not work properly?

Yes.

> And if the answer is yes, what may possibly cause this issue?

Some required external CLI tools failed to get installed.

> So maybe it's related to upstream image?

Again, yes. The upstream AdoptOpenJdk Docker image was temporarily broken, but it should be [fixed by now](https://github.com/AdoptOpenJDK/openjdk-docker/issues/445).

**Comment by BennyThink** [comment]
hi @sschuberth , many thanks for you real quick answer on this!

Seems previously I was in a bad luck for the upstream problem. 

As you mentioned above, AdoptOpenJdk was broken for a while and it should be okay now. But I still get the same issue - `/opt/ort/bin/ort requirements` quits with non-zero exit code. I've prune all my images and I'm sure the adoptopenjdk:11-jre-hotspot-bionic was 18.04.

From my testing, some other  tools, such as `Askalono`, `BoyterLc` don't even exists in Dockerfile - maybe we need to add download and add these packages?

**Comment by sschuberth** [comment]
From the "Scanners" section only ScanCode is really required, and `ort requirements` would only fail if ScanCode is not present. But for all other tools you should see the `*` marker which denotes the tool was found in the required version in the Docker image.

**Comment by BennyThink** [comment]
Many thanks for your tips! It turns out it was my mistake that had cause `yarn` and `bower` failed to install.

I think I can close this issue now.
